cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from products import views


home_page = [
    # path('', views.get_home_page, name='home'),
    path('categories/new/', views.CategoryCreateView.as_view(), name='create'),
    path('categories/', views.CategoryView.as_view(), name='category'),
    path('category-update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category_delete'),
    # path('cart/products/', views.ProductView.as_view(), name='cart/products'),
    path('products/', views.ProductAllView.as_view(), name='product'),

    path('', views.ProductListView.as_view(), name='home'),
    path('product/new/', views.ProductCreateView.as_view(), name='product_create'),
    path('product-delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('product-update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),

    path('cart/add/', views.cart, name='cart'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_page)),
    path('cart/', include('cart.urls', namespace='cart')),
]

cart/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

from django.core.validators import RegexValidator

from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=60, 
        verbose_name='name',
        unique=True,
        validators=[RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$')]
    )
    description = models.TextField(
        verbose_name='description',
    )
    status = models.BooleanField(
        default=True
    )

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['-id']


class Product(models.Model):
    name = models.CharField(
        max_length=60, 
        verbose_name='name',
        null=False,
        blank=False,
        unique=True,
    )
    description = models.TextField(
        verbose_name='description',
    )
    status = models.BooleanField(
        default=True,
    )
    category_id = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        null = True,
        related_name='products',
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        null=False,
        blank=False,
    )

    def __str__(self):
        return f'{self.name} - {self.description}'
    
    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['-id']


class Cart(models.Model):
    products = models.ManyToManyField(Product, through='CartItem')

    def __str__(self):
        return f"Cart {self.pk}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Cart {self.cart.pk}"

# class CartItem(models.Model):
#     # user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=1)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(required=False, choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

products/forms.py
from django import forms
from django.contrib.auth import get_user_model

from products.models import Category, Product, CartItem
from django.core.validators import RegexValidator


class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=60, 
        validators=[RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$', message='Используйте только буквы')],
        required=True,
    )
    status = forms.BooleanField(required=False)

    def clean_email(self):
            description = self.cleaned_data['description']
            if not description:
                raise forms.ValidationError('This field is required')
            return description

    class Meta:
        model = Category
        fields = ('name', 'description', 'status')
        labels = {
            'name': 'Category name',
            'description': 'Category description',
            'status': 'Category status',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class ProductForm(forms.ModelForm):
    name = forms.CharField(
        max_length=60, 
        validators=[RegexValidator(regex='^[a-zA-Zа-яА-Я ]+$', message='Используйте только буквы')],
        required=True,
    )
    class Meta:
        model = Product
        fields = ('name', 'description', 'status', 'category_id', 'price')
        labels = {
            'name': 'Product name',
            'description': 'Product description',
            'status': 'Product status',
            'category_id': 'Product category',
            'price': 'Product price',
        }
        category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label="Select category",
        widget=forms.Select(attrs={'class': 'form-control'})
        )      
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'category_id': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


# class AddToCartForm(forms.Form):
#     quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control', 'value': 1}))
#     product_id = forms.IntegerField(widget=forms.HiddenInput())

#     def add_to_cart(self, user):
#         product_id = self.cleaned_data['product_id']
#         quantity = self.cleaned_data['quantity']

#         try:
#             cart_item = CartItem.objects.get(product_id=product_id)
#             cart_item.quantity += quantity
#             cart_item.save()
#         except CartItem.DoesNotExist:
#             CartItem.objects.create(product_id=product_id, quantity=quantity)

# class UserForm(forms.Form):
#     class Meta:
#         model = get_user_model()
#         fields = (
#             'id',
#             'username',
#         )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from decimal import Decimal
from products.models import Product, CartItem
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    print(form.is_valid())
    for field in form:
        print("Field Error:", field.name,  field.errors)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )
        
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    print(cart)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # for item in cart:
    #     item['price'] = Decimal(item['price'])
    #     item['quantity'] = 0 
    #     item['total_price'] = item['price'] * item['quantity']
    #     item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    print(cart)
    return render(request, 'cart.html', {'cart': cart})

products/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import TemplateView, FormView

# from django.contrib.auth import login

# from django.contrib.auth.decorators import login_required

from products.models import Category, Product, Cart, CartItem

from products.forms import CategoryForm, ProductForm

from cart.forms import CartAddProductForm


# def get_home_page(request):
    
#     return render(request, 'index.html')

class ProductListView(TemplateView):
    template_name = 'index.html'
    all_products = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'products': Product.objects.all(),
            'categories': Category.objects.all(),
        })
        return context 
    
    def add_to_cart(request, product_id):
        product = get_object_or_404(Product, id=product_id)
        cart, _ = Cart.objects.get_or_create(pk=request.session.get('cart_id'))
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

        if not created:
            cart_item.quantity += 1
            cart_item.save()

        request.session['cart_id'] = cart.pk
        return redirect('cart')

def cart(request):
    # cart = Cart.objects.get(pk=request.session.get('cart_id'))
    try:
        cart = Cart.objects.get(pk=request.session.get('cart_id'))
    except Cart.DoesNotExist:
        cart = None
    return render(request, 'cart.html', {'cart': cart})

class CategoryView(TemplateView):
    template_name = 'category.html'
    all_category = Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'categories': Category.objects.all(),
        })
        return context


class CategoryCreateView(TemplateView):
    template_name = 'category_create.html'

    def get(self, request):
        form = CategoryForm()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        if request.POST:
            form = CategoryForm(request.POST)
            if form.is_valid():
                form.save() 
                return redirect('category')  
        context = {'form': form, 'data': request.POST}
        return render(request, self.template_name, context)


class CategoryUpdateView(TemplateView):
    template_name = 'cat_update.html'

    def get(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        form = CategoryForm(instance=category)
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('category')
        context = {'form': form}
        return render(request, self.template_name, context)


class CategoryDeleteView(TemplateView):
    template_name = 'category_delete.html'

    def get(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        context = {'category': category}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        category.delete()
        return redirect('category')


class ProductView(TemplateView):
    template_name = 'cart.html'
    all_products = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'products': Product.objects.all(),
            'categories': Category.objects.all(),
        })
        return context    


class ProductAllView(TemplateView):
    template_name = 'product.html'
    all_products = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'products': Product.objects.all(),
            'categories': Category.objects.all(),
        })
        return context          
    

def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    return render(
        request, 'cart.html', {'product': product,'cart_product_form': cart_product_form})


class ProductCreateView(TemplateView):
    template_name = 'product_create.html'

    def get(self, request):
        form = ProductForm()
        categories = Category.objects.all() 
        return render(request, self.template_name, {'form': form, 'categories': categories})
    
    def post(self, request):
        if request.POST:
            form = ProductForm(request.POST)
            if form.is_valid():
                form.save() 
                return redirect('home') 
        categories = Category.objects.all()        
        context = {'form': form, 'categories': categories, 'data': request.POST}
        return render(request, self.template_name, context)
    

class ProductDeleteView(TemplateView):
    template_name = 'product_delete.html'

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        context = {'product': product}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        return redirect('home')    
    

class ProductUpdateView(TemplateView):
    template_name = 'product_update.html'

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(instance=product)
        categories = Category.objects.all() 
        context = {'form': form, 'categories': categories, 'product': product}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product')
        context = {'form': form, 'product': product}
        return render(request, self.template_name, context)

   
# def register(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('home')
#     else:
#         form = UserCreationForm()
#     return render(request, 'register.html', {'form': form})


# def add_to_cart(request):
#     form = AddToCartForm(request.POST)

#     if form.is_valid():
#         form.add_to_cart(request)
#         messages.success(request, 'Товар добавлен в корзину')
#     else:
#         messages.error(request, 'Не удалось добавить товар в корзину')

#     return redirect('basket.html', product_id=form.cleaned_data['product_id'])


# def view_cart(request):
#     cart_items = CartItem.objects.filter(user=request.user)

#     return render(request, 'basket.html', {'cart_items': cart_items})

templates/cart.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>


<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

      <a class="navbar-brand" href="#">Online-shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'category' %}">Category</a>
          </li>


          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Product</a>
          </li>

        </ul>

        <form class="d-flex">

          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'product_create' %}">Create new product</a>
          </li>

        </form>

      </div>

    </div>
    
  </nav>


  {% block content %}
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
        <tr>
            <th>Товар</th>
            <th>Описание</th>
            <th>Обновить кол-во</th>
            <th>Удалить</th>
            <th>Цена за шт</th>
            <th>Общая стоимость</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart.item %}
            {% with product=item.product %}
                <tr>
                    <td>
                      <a href="{{ product.get_absolute_url }}"></a>
                      {{ product.name }}
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="Обновить">
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                        <td class="num">{{ item.price }}</td>
                        <td class="num">{{ item.total_price }}</td>
                    </td>
                    <td>
                        {{ item.quantity }}
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}  
          <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ cartitem.get_total_price }}</td>
          </tr>    
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'home' %}" class="button light">Вернуться</a>
  </p>
{% endblock %}  

templates/cat_update.html
<!DOCTYPE html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Online-shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'category' %}">Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product' %}">Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create' %}">Create</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'home' %}" tabindex="-1" aria-disabled="true">home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<html>
  <head>
    <meta charset="utf-8">
    <title>Edit category</title>
  </head>
  <body>
    <h1>Edit category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.errors }}

      <div class="form-group mx-sm-3 mb-2">
        <label for="id_name" class="form-control" >Name:</label>
        <input type="text" class="form-control" name="name"  {{ form.name }} >
      </div>

      <div class="form-group mx-sm-3 mb-2">
        <label for="id_description" class="form-control" >Description:</label>
        {{ form.description }}
      </div>

      <div class="form-group mb-3 form-check">
        <label for="id_status" class="form-check-label" >Status:</label>
        {{ form.status }}
      </div>
      
      <button type="submit" class="btn btn-primary" >Save</button>
    </form>
  </body>
</html>

templates/category_create.html
{% load static %}

<!DOCTYPE html>
<head>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">

    <a class="navbar-brand" href="{% url 'home' %}">Online-shop</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'category' %}">Category</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'product' %}">Product</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'home' %}" tabindex="-1" aria-disabled="true">home</a>

        </li>

      </ul>

    </div>

  </div>

</nav>

<form method="post">

  {% csrf_token %}
  {{ form.errors }}

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_name">Name:</label>
    <input type="text" class="form-control" name="name"  value="{{ data.name }}" required>
  </div>

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_description">Description:</label>
    <input  type="text" class="form-control" name="description" value="{{ data.description }}" reguired></input>
  </div>

  <div class="form__group form__checkbox">
    {{ form.status.label_tag }}
    {{ form.status }}
  </div>

  <button type="submit" class="btn btn-primary">Create</button>

</form>

templates/product_create.html
<!DOCTYPE html>
<head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Online-shop</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'category' %}">Category</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'product' %}">Product</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'home' %}" tabindex="-1" aria-disabled="true">home</a>
        </li>

      </ul>

    </div>

  </div>

</nav>

<form method="post">

  {% csrf_token %}
  {{ form.errors }}

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_name">Name:</label>
    <input type="text" class="form-control" name="name" value="{{ data.name }}" required>
  </div>

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_description">Description:</label>
    <input  type="text" class="form-control" name="description" value="{{ data.description }}" reguired></input>
  </div>

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_category">Category:</label>

    <select class="form-control" name="category_id">
      {% for category in categories %}
      <option value="{{ category.id }}">{{ category.name }}</option>
      {% endfor %}
    </select>

  </div>

  <div class="form-group mx-sm-3 mb-2">
    <label for="id_price">Price:</label>
    <input type="number" class="form-control" name="price" step="0.01" value="{{ data.price }}" required>
  </div>

  <div class="form__group form__checkbox">
    {{ form.status.label_tag }}
    {{ form.status }}
  </div>

  <button type="submit" class="btn btn-primary">Create</button>

</form>

templates/product_update.html
<!DOCTYPE html>
<head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">

    <a class="navbar-brand" href="{% url 'home' %}">Online-shop</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'category' %}">Category</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product' %}">Product</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'home' %}" tabindex="-1" aria-disabled="true">home</a>
        </li>

      </ul>

    </div>

  </div>

</nav>

<html>

  <head>
    <meta charset="utf-8">
    <title>Edit category</title>
  </head>

  <body>

    <h1>Edit category</h1>

    <form method="post">

      {% csrf_token %}
      {{ form.errors }}

      <div class="form-group mx-sm-3 mb-2">
        <label for="id_name" class="form-control" >Name:</label>
        <input type="text" class="form-control" name="name"  {{ form.name }} >
      </div>

      <div class="form-group mx-sm-3 mb-2">
        <label for="id_description" class="form-control" >Description:</label>
        {{ form.description }}
      </div>

      <div class="form-group mx-sm-3 mb-2">
        <label for="{{ form.category_id.id_for_label }}">Category:</label>

        <select class="form-control" name="{{ form.category_id.name }}">
          {% for category in categories %}
          <option value="{{ category.id }}" {% if form.category_id.value == category.id %}selected{% endif %}>{{ category.name }}</option>
          {% endfor %}
        </select>
        
      </div>

      <div class="form-group mx-sm-3 mb-2">
        <label for="id_price">Price:</label>
        <input type="number" class="form-control" name="price" step="0.01" value="{{ form.instance.price }}" required>
      </div>

      <div class="form-group mb-3 form-check">
        <label for="{{ form.status.id_for_label }}" class="form-check-label">Status:</label>
        {{ form.status }}
      </div>
      
      <button type="submit" class="btn btn-primary" >Save</button>

    </form>

  </body>

</html>